# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ami-tiogapass"
BBFILE_PATTERN_ami-tiogapass = "^${LAYERDIR}/"
BBFILE_PRIORITY_ami-tiogapass = "12"
LAYERSERIES_COMPAT_ami-tiogapass = "walnascar"

# Product generation identifier
PRODUCT_GENERATION = "OT"

# Override the LED manager provider for tiogapass.
PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native ?= "intel-led-manager-config-native"
