BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "amidevkit-2700"
BBFILE_PATTERN_amidevkit-2700 := "^${LAYERDIR}/"
BBFILE_PRIORITY_amidevkit-2700 = "20"
LAYERSERIES_COMPAT_amidevkit-2700 = "walnascar"
LAYERDEPENDS_amidevkit-2700 = "meta-ami aspeed-sdk-layer ast2700-sdk-layer"