# Template for EXTLOG messages
# "<timestamp> <MessageId>,<MessageArgs>"
template(name="ExtlogTemplate" type="list") {
    property(name="timereported" dateFormat="rfc3339")
    constant(value=" ")
    property(name="$!EXTLOG_MESSAGE_ID")
    constant(value=",")
    property(name="$!EXTLOG_MESSAGE_ARGS")
    constant(value="\n")
}

# If the journal entry has a EXTLOG MessageId, save as a extendedlog
if ($!EXTLOG_MESSAGE_ID != "") then {
   action(type="omfile" file="/etc/extlog/extended.log" template="ExtlogTemplate")
}
