#Host console log

module(load="imuxsock" SysSock.Use="off")

template(name="ConsoleTemplate" type="string" string="%rawmsg%")

ruleset(name="ConsolettyS0Ruleset") {
  action(type="omfile" file="/var/log/obmc-console/hostlog_ttyS0.log" template="ConsoleTemplate")
}
ruleset(name="ConsolettyS1Ruleset") {
  action(type="omfile" file="/var/log/obmc-console/hostlog_ttyS1.log" template="ConsoleTemplate")
}
ruleset(name="ConsoleRuleset") {
  action(type="omfile" file="/var/log/obmc-console/hostlog.log" template="ConsoleTemplate")
}
# Custom socket for serial console logs.
input(type="imuxsock"
  Socket="/run/rsyslog/console/hostlog_ttyS0"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsolettyS0Ruleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/hostlog_ttyS1"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsolettyS1Ruleset")

input(type="imuxsock"
  Socket="/run/rsyslog/console/hostlog"
  CreatePath="on"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="ConsoleRuleset")

$EscapeControlCharactersOnReceive off
$DropTrailingLFOnReception off

