# Drop logs from systemd-related daemons
if ($programname == 'systemd' or $programname == 'systemd-journald' or $programname == 'systemd-logind') then {
    stop
}

# Store logs in appropriate files based on severity while excluding local1 and local3 where necessary
if ($syslogfacility-text == "local1") then {
    action(type="omfile" file="/var/log/audit.log")}
if ($syslogpriority-text == "debug" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/debug.log")}
if ($syslogpriority-text == "info" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/info.log")}
if ($syslogpriority-text == "notice" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/notice.log")}
if ($syslogpriority-text == "warning" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/warning.log")}
if ($syslogpriority-text == "err" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/err.log")}
if ($syslogpriority-text == "crit" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/crit.log")}
if ($syslogpriority-text == "alert" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/alert.log")}
if ($syslogpriority-text == "emerg" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/emerg.log")}
if ($syslogfacility-text == "kern" and not ($syslogfacility-text == "local1" or $syslogfacility-text == "local3")) then {
    action(type="omfile" file="/var/log/kern.log")}
