#!/usr/bin/env python3
"""
gen_fwupd.py — generates fwupd.sh (safe quoting; no f-strings in shell)
Features:
- Detects a single component image by imagePatterns; selects @IMAGE@.
- PURPOSE via common.sh: detect_manifest_purpose(); FWVER via MANIFEST/manifest.json.
- Target discovery at runtime via common.sh:
    get_pushuri_targets
    filter_targets_by_manifest_purpose
- exec.prepost: "per-target" (default) or "global"
- exec.parallel: true|false (per-target loops)
- exec.targetMode: "per-target" (default) or "batched"
- Tokens: @IMAGE@ @DIR@ @TARGET@ @TARGETS@ @TARGETSFILE@ @IMAGEPATH@
"""

import argparse, json, os, shlex, sys

def q(s): return shlex.quote(str(s))

def replace_shell_tokens(cmd: str) -> str:
    return (cmd
            .replace('@IMAGE@', '$IMAGE_PATH')
            .replace('@DIR@', '$IMAGE_DIR')
            .replace('@TARGET@', '$TARGET')
            .replace('@IMAGEPATH@', '$CUSTOM_IMAGE_PATH')
            .replace('@TARGETS@', '$TARGETS')
            .replace('@TARGETSFILE@', '$TARGETS_FILE'))

def tpl_arg(arg: str) -> str:
    return {
        '@IMAGE@': '$IMAGE_PATH',
        '@DIR@': '$IMAGE_DIR',
        '@TARGET@': '$TARGET',
        '@IMAGEPATH@': '$CUSTOM_IMAGE_PATH',
        '@TARGETS@': '$TARGETS',
        '@TARGETSFILE@': '$TARGETS_FILE',
    }.get(arg, q(arg))

def header(common_path: str, log_path: str, image_root: str) -> str:
    L = []
    L += [
        "#!/bin/sh",
        "# Auto-generated by gen_fwupd.py — DO NOT EDIT",
        "# Single-component, multi-target (Purpose-driven) firmware updater",
        "",
        "set -eu",
        ': "${LOG_FILE=' + q(log_path) + '}"',
        "export LOCAL_FILE=0",
        ". " + q(common_path),
        "",
        "# --- Global abort trap: ensures Redfish abort on any failure -------------",
        "_fwupd_abort_trap() {",
        "  rc=$?",
        '  _comp="${FOUND_COMP:-unknown}"',
        '  _tgt="${TARGET:-}"',
        '  _line="${LINENO:-?}"',
        '  _reason="Update failed (component=${_comp}, target=${_tgt}, rc=${rc}, line=${_line})"',
        '  redfish_log_abort "${_reason}" || true',
        "  set_task_status Exception || true",
        "  set_progress 100 || true",
        '  exit "$rc"',
        "}",
        "",
        "_fwupd_cleanup_tmp() {",
        '  [ -n "${TARGETS_FILE:-}" ] && [ -f "$TARGETS_FILE" ] && rm -f "$TARGETS_FILE" || :',
        '  clear_pushuri_target_and_busy_status || true',
        "}",
        "trap '_fwupd_abort_trap' ERR",
        "trap '_fwupd_cleanup_tmp' EXIT",
        "",
        '[ "$#" -eq 1 ] || { echo "Usage: $0 IMAGE_KEY" >&2; exit 2; }',
        'IMAGE_KEY="$1"',
        "",
        'IMAGE_ROOT="' + image_root.replace('"','\\"') + '"',
        'IMAGE_DIR="$IMAGE_ROOT/$IMAGE_KEY"',
        'dir="${IMAGE_DIR%/}"',
        "",
        'IMG_BASENAME="$(basename "$IMAGE_KEY")"',
        'set_img_obj "$IMG_BASENAME"',
        "",
        'FOUND_COMP=""',
        'IMAGE_PATH=""',
        'PURPOSE="$(detect_manifest_purpose "$dir")"',
        "",
        "# Parse FWVER (fallback to IMG_BASENAME)",
        'FWVER="$(',
        '  awk -F= \'/^version=/{print $2}\' "$dir/MANIFEST" 2>/dev/null ||',
        '  awk -F\'"\' \'/"version"/{print $4}\' "$dir/manifest.json" 2>/dev/null',
        ')"',
        '[ -n "$FWVER" ] || FWVER="$IMG_BASENAME"',
        "export FWVER",
        "",
        'log "Manifest purpose: ${PURPOSE:-<unknown>}"',
        "",
    ]
    return "\n".join(L) + "\n"

def emit_detector(name: str, patterns):
    patt = patterns or []
    L = []
    L.append('# Detect ' + name)
    L.append('if [ -z "$FOUND_COMP" ]; then')
    for p in patt:
        L.append('  if [ -f "$dir/' + p + '" ]; then FOUND_COMP="' + name + '"; IMAGE_PATH="$dir/' + p + '"; fi')
    L.append('  [ -z "$FOUND_COMP" ] || :')
    L.append('  if [ -z "$FOUND_COMP" ] && [ -f "$dir/image-' + name + '" ]; then FOUND_COMP="' + name + '"; IMAGE_PATH="$dir/image-' + name + '"; fi')
    L.append('else')
    conds = ['[ -f "$dir/' + p + '" ]' for p in patt] + ['[ -f "$dir/image-' + name + '" ]']
    L.append('  if ' + ' || '.join(conds) + '; then')
    L.append('    log "ERROR: multiple image types detected: $FOUND_COMP and ' + name + '"')
    L.append('    exit 1')
    L.append('  fi')
    L.append('fi')
    L.append('')
    return "\n".join(L) + "\n"

def emit_step(step: dict) -> str:
    a = (step.get('action') or '').lower()
    if a == 'shell':
        cmd = step.get('cmd')
        if not cmd: raise ValueError("shell step requires 'cmd'")
        return '  run_shell "' + replace_shell_tokens(cmd).replace('"','\\"') + '"\n'
    if a in ('script','tool'):
        path = step.get('path')
        if not path: raise ValueError(a + " step requires 'path'")
        fun = 'run_script' if a == 'script' else 'run_tool'
        argline = ' '.join(tpl_arg(x) for x in step.get('args', []))
        return '  ' + fun + ' ' + q(path) + ' ' + argline + '\n'
    if a == 'dbus':
        dest=step.get('dest'); obj=step.get('obj'); iface=step.get('iface'); meth=step.get('method')
        if not all([dest,obj,iface,meth]): raise ValueError("dbus step requires dest/obj/iface/method")
        sig = step.get('signature',''); argline = ' '.join(tpl_arg(x) for x in step.get('args', []))
        return '  run_dbus ' + q(dest) + ' ' + q(obj) + ' ' + q(iface) + ' ' + q(meth) + ' ' + q(sig) + ' ' + argline + '\n'
    if a == 'function':
        name = step.get('name')
        if not name: raise ValueError("function step requires 'name'")
        argline = ' '.join(tpl_arg(x) for x in step.get('args', []))
        return '  ' + name + ' ' + argline + '\n'
    raise ValueError("Unsupported action: " + a)

def _exec_opts(comp: dict):
    ex = comp.get('exec') or {}
    prepost = (ex.get('prepost') or 'per-target').strip().lower()
    parallel = bool(ex.get('parallel', False))
    target_mode = (ex.get('targetMode') or 'per-target').strip().lower()
    filter_by_purpose = bool(ex.get('filterByPurpose', True))  # default: true
    maxp = ex.get('maxParallel')  # reserved; not enforced here
    return prepost, parallel, target_mode, filter_by_purpose, maxp

def emit_component_functions(comp: dict) -> str:
    name = comp['name']
    pre = comp.get('pre') or []
    flash = comp.get('flash') or []
    post = comp.get('post') or []
    if not flash:
        raise ValueError("component '" + name + "' missing 'flash' steps")

    out = []
    # prepare()
    out += ['do_' + name + '_prepare() {']
    if pre:
        out += ['  section "' + name.upper() + ' prepare"']
        for st in pre:
            out.append(emit_step(st).rstrip())
    else:
        out += ['  :']
    out += ['}', '']

    # flash_only()
    out += ['do_' + name + '_flash_only() {',
            '  section "' + name.upper() + ' update"',
            '  set_task_status Starting; set_progress 40',
            '  redfish_log_fw_evt start || true',
            '  set_task_status Running; set_progress 60']
    for st in flash:
        out.append(emit_step(st).rstrip())
    out += ['  redfish_log_fw_evt staged || true',
            '  set_progress 95',
            '  set_task_status Completed; set_progress 100',
            '  redfish_log_fw_evt success || true',
            '}',
            '']

    # cleanup()
    out += ['do_' + name + '_cleanup() {']
    if post:
        out += ['  section "' + name.upper() + ' cleanup"']
        for st in post:
            out.append(emit_step(st).rstrip())
    else:
        out += ['  :']
    out += ['}', '']

    # legacy per-target wrapper (pre -> flash -> post)
    out += ['do_' + name + '() {']
    if pre:   out += ['  do_' + name + '_prepare']
    else:     out += ['  :']
    out += ['  do_' + name + '_flash_only']
    if post:  out += ['  do_' + name + '_cleanup']
    else:     out += ['  :']
    out += ['}', '']

    return "\n".join(out) + "\n"

def emit_target_init_block_for_component(comp: dict) -> str:
    default_targets = comp.get('defaultTargets', [])
    default_targets_str = ' '.join(default_targets) if default_targets else ''
    ex = comp.get('exec') or {}
    filter_by_purpose = bool(ex.get('filterByPurpose', True))
    
    L = []
    L.append('  # --- Discover Push-URI targets ---')
    L.append('  ALL_TARGETS="$(get_pushuri_targets)"')
    L.append('  log "Push-URI targets (received): ${ALL_TARGETS:-<none>}"')
    
    if filter_by_purpose:
        L.append('  # Filter targets by manifest purpose')
        L.append('  RESOLVED_TARGETS="$(filter_targets_by_manifest_purpose "$ALL_TARGETS")"')
        L.append('  if [ -n "$RESOLVED_TARGETS" ]; then')
        L.append('    log "Validated targets (Purpose=${PURPOSE:-}): $RESOLVED_TARGETS"')
        L.append('  else')
        if default_targets_str:
            L.append('    log "WARN: No valid targets for Purpose=${PURPOSE:-}, using default targets"')
            L.append('    RESOLVED_TARGETS="' + default_targets_str + '"')
            L.append('    log "Default targets: $RESOLVED_TARGETS"')
        else:
            L.append('    log "ERROR: No valid targets for Purpose=${PURPOSE:-} and no default targets specified"')
            L.append('    set_task_status Exception || true')
            L.append('    exit 1')
        L.append('  fi')
    else:
        L.append('  # Skip purpose filtering (filterByPurpose=false)')
        L.append('  if [ -n "$ALL_TARGETS" ]; then')
        L.append('    RESOLVED_TARGETS="$ALL_TARGETS"')
        L.append('    log "Using all Push-URI targets (no purpose filter): $RESOLVED_TARGETS"')
        L.append('  else')
        if default_targets_str:
            L.append('    log "WARN: No Push-URI targets, using default targets"')
            L.append('    RESOLVED_TARGETS="' + default_targets_str + '"')
            L.append('    log "Default targets: $RESOLVED_TARGETS"')
        else:
            L.append('    log "ERROR: No Push-URI targets and no default targets specified"')
            L.append('    set_task_status Exception || true')
            L.append('    exit 1')
        L.append('  fi')
    
    L.append('  TARGETS="$RESOLVED_TARGETS"; export TARGETS')
    L.append('  TARGETS_FILE=""')
    L.append('  if command -v mktemp >/dev/null 2>&1; then')
    L.append('    TARGETS_FILE="$(mktemp)"; export TARGETS_FILE')
    L.append('    printf "%s\\n" $RESOLVED_TARGETS >"$TARGETS_FILE"')
    L.append('  fi')
    return "\n".join(L) + "\n"

def trailer_dispatch(components) -> str:
    arms = []
    for c in components:
        n=c['name']
        prepost, parallel, target_mode, filter_by_purpose, _maxp = _exec_opts(c)
        arm = ' ' + n + ')\n' + emit_target_init_block_for_component(c)

        if target_mode == 'batched':
            arm += (
                '  do_' + n + '_prepare\n'
                '  do_' + n + '_flash_only\n'
                '  do_' + n + '_cleanup\n'
                '  ;;\n'
            )
        else:
            if prepost == 'global':
                arm += (
                    '  do_' + n + '_prepare\n'
                    '  if [ -n "$RESOLVED_TARGETS" ]; then\n'
                )
                if parallel:
                    arm += (
                        '    PIDS=""\n'
                        '    for TARGET in $RESOLVED_TARGETS; do\n'
                        '      (\n'
                        '        export TARGET\n'
                        '        do_' + n + '_flash_only\n'
                        '      ) & PIDS="$PIDS $!"\n'
                        '    done\n'
                        '    statuses=0\n'
                        '    for p in $PIDS; do\n'
                        '      wait "$p" || statuses=$((statuses+1))\n'
                        '    done\n'
                        '    if [ "$statuses" -ne 0 ]; then\n'
                        '      exit 1\n'
                        '    fi\n'
                    )
                else:
                    arm += (
                        '    for TARGET in $RESOLVED_TARGETS; do\n'
                        '      export TARGET\n'
                        '      do_' + n + '_flash_only\n'
                        '    done\n'
                    )
                arm += (
                    '  else\n'
                    '    TARGET=""\n'
                    '    do_' + n + '_flash_only\n'
                    '  fi\n'
                    '  do_' + n + '_cleanup\n'
                    '  ;;\n'
                )
            else:
                arm += (
                    '  if [ -n "$RESOLVED_TARGETS" ]; then\n'
                    '    for TARGET in $RESOLVED_TARGETS; do\n'
                    '      export TARGET\n'
                    '      do_' + n + '\n'
                    '    done\n'
                    '  else\n'
                    '    TARGET=""\n'
                    '    do_' + n + '\n'
                    '  fi\n'
                    '  ;;\n'
                )
        arms.append(arm)

    return (
        '[ -n "$FOUND_COMP" ] || { log "ERROR: no known image found in $IMAGE_DIR"; exit 1; }\n'
        '[ -n "$IMAGE_PATH" ] || { log "ERROR: internal: IMAGE_PATH not set"; exit 1; }\n\n'
        'log "Detected component: $FOUND_COMP"\n'
        'log "Image selected: $IMAGE_PATH"\n\n'
        '# Export FWTYPE/FWVER for Redfish/journald logging\n'
        'case "$FOUND_COMP" in\n'
        '  bmc)  FWTYPE="BMC"  ;;\n'
        '  bios) FWTYPE="BIOS" ;;\n'
        '  cpld) FWTYPE="CPLD" ;;\n'
        '  raid) FWTYPE="RAID" ;;\n'
        '  *)    FWTYPE="$(printf "%s" "$FOUND_COMP" | tr \'[:lower:]\' \'[:upper:]\')" ;;\n'
        'esac\n'
        'export FWTYPE FWVER\n\n'
        'log "Check firmware update priority"\n'
        'verify_multifirmware_rules $dir\n'
        'if [[ "$?" = "${RET_FAILED}" ]];then log "Multiple firmware updates failed - priority error"; exit 2;fi\n\n'
        'case "$FOUND_COMP" in\n'
        + ''.join(arms) +
        '  *)\n'
        '    log "ERROR: unsupported component: $FOUND_COMP"; exit 2 ;;\n'
        'esac\n'
    )

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--json', required=True, help='Path to fwupd.json')
    ap.add_argument('--out', required=True, help='Output fwupd.sh path')
    ap.add_argument('--common', default='/usr/libexec/fwupd/common.sh',
                    help='Path to common.sh sourced at runtime')
    args = ap.parse_args()

    try:
        with open(args.json, 'r', encoding='utf-8') as f:
            cfg = json.load(f)
    except Exception as e:
        print("ERROR: reading JSON '{}': {}".format(args.json, e), file=sys.stderr)
        sys.exit(2)

    log_path   = cfg.get('log', '/var/log/fwupd/fwupd.log')
    image_root = cfg.get('imageRoot', '/image-path')
    components = cfg.get('components')
    if not isinstance(components, list) or not components:
        print("ERROR: JSON must contain a non-empty 'components' array", file=sys.stderr)
        sys.exit(2)

    parts = [ header(args.common, log_path, image_root) ]
    for comp in components:
        name = comp.get('name')
        if not name:
            print("ERROR: a component is missing 'name'", file=sys.stderr)
            sys.exit(2)
        parts.append(emit_detector(name, comp.get('imagePatterns') or []))

    for comp in components:
        parts.append(emit_component_functions(comp))

    parts.append(trailer_dispatch(components))

    out_path = os.path.expanduser(args.out)
    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(parts))
    os.chmod(out_path, 0o755)

if __name__ == '__main__':
    main()
