BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*.bbappend \
           "

BBFILE_COLLECTIONS += "meta-ami-devkit"
BBFILE_PATTERN_meta-ami-devkit = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ami-devkit = "20"

LAYERVERSION_meta-ami-devkit = "1"
LAYERSERIES_COMPAT_meta-ami-devkit = "walnascar"
LAYERDEPENDS_meta-ami-devkit = "meta-ami evb evb-aspeed evb-ast2600"