# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBMASK += "meta-core/meta-restricted/recipes-intel/images/intel-platforms.bbappend"
BBMASK += "meta-core/meta-intel/recipes-intel/images/intel-platforms.bbappend"
BBMASK += "meta-core/meta-restricted/recipes-optee"
BBMASK += "meta-ami/meta-evb/meta-evb-aspeed/meta-evb-ast2700/recipes-phosphor/pmci/libmctp-intel_git.bb"

BBFILE_COLLECTIONS += "aspeed-sdk-layer"
BBFILE_PATTERN_aspeed-sdk-layer := "^${LAYERDIR}/"
LAYERVERSION_aspeed-sdk-layer = "1"
BBFILE_PRIORITY_aspeed-sdk-layer = "11"
LAYERSERIES_COMPAT_aspeed-sdk-layer = "nanbield  scarthgap"

# Provide a variable that points the base of the aspeed-sdk layer.
ASPEEDSDKBASE = '${@os.path.normpath("${LAYERDIR}/")}'

BBFILES_DYNAMIC += " \
    meta-arm:${LAYERDIR}/dynamic-layers/arm-layer/recipes-*/*/*.bb \
    meta-arm:${LAYERDIR}/dynamic-layers/arm-layer/recipes-*/*/*.bbappend \
    zephyrcore:${LAYERDIR}/dynamic-layers/zephyrcore-layer/recipes-*/*/*.bb \
    zephyrcore:${LAYERDIR}/dynamic-layers/zephyrcore-layer/recipes-*/*/*.bbappend \
"

IMAGE_INSTALL:append = "${@bb.utils.contains('IMAGE_FEATURES', 'onetree-fwupdate', ' nv-sync ','', d)}"

ENABLE_BONDING = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'onetree-network-bonding-support', 'network-bond', '', d)}"
