#!/bin/sh

hostname=$(hostname)
hw_mac=$(cat /sys/class/net/eth0/address | tr -d ":")
bmc_mac_format="^AMIOT-[a-f0-9]{12}$"
mac_default="AMIOT-$hw_mac"
if [[ "$hostname" == "intel-obmc" ]]; then
	hostnamectl set-hostname "$mac_default"	
fi
