#!/bin/bash
set -eo pipefail

# Check the /sys/class/spi_master/spi0/device/current_boot and tell if it's running on the primary or the secondary flash.

CURRENT_BOOT="/sys/class/spi_master/spi0/device/current_boot"
SLOT_FILE="/run/media/slot"

# Create directory if not exist
mkdir -p "$(dirname "${SLOT_FILE}")"

# Write slot info
if [ "$(cat "$CURRENT_BOOT")" -eq 0 ]; then
    echo "0" > ${SLOT_FILE}
else
    echo "1" > ${SLOT_FILE}
fi
