LOCALCONF_VERSION = "4"
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-ast2600"
BBFILE_PATTERN_evb-ast2600 = "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-ast2600 = "11"
LAYERSERIES_COMPAT_evb-ast2600 = "nanbield scarthgap"

# uncomment below 2 lines to enable SW eMMC support
#EXTRA_IMAGE_FEATURES:append = " emmc-sw-ami "
#IMAGE_FSTYPES += "wic.xz mmc-ext4-tar"
#bootlogo

EXTRA_IMAGE_FEATURES:append = " onetree-bootlogo"

# SW eMMC support - configs start
IMAGE_FEATURES[validitems] += "emmc-sw-ami"
OVERRIDES:append = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'emmc-sw-ami', ':emmc-sw-ami:df-phosphor-mmc:ast-mmc', '', d)}"

DISTRO_FEATURES += "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'emmc-sw-ami', 'phosphor-mmc', '', d)}"
MACHINE_FEATURES += "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'emmc-sw-ami', 'ast-mmc', '', d)}"

WKS_FILE="emmc-ami.wks.in"

IMAGE_OVERHEAD_FACTOR:emmc-sw-ami = "1.0"
IMAGE_ROOTFS_EXTRA_SPACE:emmc-sw-ami = "4096"
BAD_RECOMMENDATIONS:remove = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'emmc-sw-ami', 'e2fsprogs-e2fsck', '', d)}"
# SW eMMC support - configs end

PRODUCT_GENERATION = "OT"
