#!/bin/sh

# Note: Dual node is not supported at this time. SOL routing is performed only for node 1.
for ROUTER in /sys/bus/platform/drivers/aspeed-uart-routing/*.uart-routing; do
        break
done

[ -L "$ROUTER" ] || exit 2

route() {
    echo -n "$1" > "$ROUTER/$2"
    echo -n "$2" > "$ROUTER/$1"
}

setup_routing() {
    echo "Enabling UART routing"

    route uart2 uart0
    route uart0 uart2
    route io0 uart3
    route uart3 io0
}

setup() {
    hostserialcfg=$(fw_printenv hostserialcfg 2> /dev/null)
    hostserialcfg=${hostserialcfg##*=}

    if [ "$hostserialcfg" = 1 ]
    then
        baud=921600
    else
        baud=115200
    fi

    echo "Configuring host UART for $baud baud"

    CONSOLE_CONF=/etc/obmc-console/server.ttyS2.conf
    cat > $CONSOLE_CONF <<-EOF
	# AMI Autogenerated by $0
	baud = $baud
	local-tty = ttyS3
	local-tty-baud = $baud
	console-id = default
	EOF
}

teardown() {
    echo "Disabling UART routing"
    route io1 uart1
}

$1
