# Prohibit general access to this service.
#restrict default ignore // Removed this configuration since it restricts all communication

restrict -4 default kod notrap nomodify nopeer noquery limited
restrict -6 default kod notrap nomodify nopeer noquery limited

restrict 127.0.0.1
restrict ::1

tinker panic 0
driftfile /var/run/ntp.drift

logfile /var/log/ntpd.log
logconfig =syncall +clockall +peerall +sysall

server -4 kong.rellim.com ca /etc/ntpsec/ntpsec-ca-certificates.crt nts iburst

