#flash-size
FLASH_SIZE = "131072"

#SectionName: "u-boot"
FLASH_UBOOT_OFFSET:flash-131072 = "0" 
FLASH_UBOOT_SIZE:flash-131072 = "4096"

#SectionName: "u-boot-env"
FLASH_UBOOT_ENV_OFFSET:flash-131072 = "4096" 
FLASH_UBOOT_ENV_SIZE:flash-131072 = "128"

#SectionName: "kernel"
FLASH_KERNEL_OFFSET:flash-131072 = "4224" 
FLASH_KERNEL_SIZE:flash-131072 = "11264"

#SectionName: "rofs"
FLASH_ROFS_OFFSET:flash-131072 = "15488" 
FLASH_ROFS_SIZE:flash-131072 = "84864"

#SectionName: "rwfs"
FLASH_RWFS_OFFSET:flash-131072 = "100352" 
FLASH_RWFS_SIZE:flash-131072 = "30656"

#SectionName: "reserved"
FLASH_RESERVED_OFFSET:flash-131072 = "131008"
FLASH_RESERVED_SIZE:flash-131072 = "64"


