# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-imx93"
BBFILE_PATTERN_evb-imx93 = "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-imx93 = "12"

LAYERSERIES_COMPAT_evb-imx93 = "walnascar"

AMI_CORE_FEATURES:remove = "onetree-kvm"