#@TYPE: Machine
#@NAME: imx93 Development Board (64bit)
#@DESCRIPTION: Machine configuration for the imx93 in 64 bits mode

DEFAULTTUNE = "cortexa55"

include conf/machine/include/imx93.inc

MACHINE_FEATURES:remove = "nxpiw612-sdio"
MACHINE_EXTRA_RRECOMMENDS:remove = " \
    firmware-nxp-wifi-nxpiw612-sdio \
    imx-m33-demos \
    kernel-module-nxp-wlan \
"

KERNEL_DEVICETREE = "freescale/imx93-11x11-frdm-bmc.dtb"

SERIAL_CONSOLES ?= "115200;ttyLP0"
SYSTEMD_AUTO_ENABLE = "enable"
IMAGE_INSTALL:append = " libmctp mctp"
AMI_CORE_FEATURES:remove = "onetree-kvm"

FLASH_SIZE = "65536"

WKS_FILE = "obmc-phosphor-image.evb-${KSOC}.wks"

ATF_PLATFORM = "${KSOC}"

UBOOT_CONFIG_BASENAME = "${CONFIG_BASENAME}"
UBOOT_DTB_NAME = "imx93-11x11-frdm-bmc.dtb"
UBOOT_CONFIG = "sd emmc fspi qspi"
UBOOT_CONFIG[sd] = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"
UBOOT_CONFIG[emmc] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_CONFIG[qspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
IMXBOOT_TARGETS[sd] = "flash_singleboot"
IMXBOOT_TARGETS[emmc] = "flash_singleboot"
IMXBOOT_TARGETS[fspi] = "flash_singleboot_flexspi"
IMXBOOT_TARGETS[qspi] = "flash_singleboot_flexspi"
IMAGE_BOOT_FILES = "u-boot.bin Image ${@' '.join([dtb.split('/')[-1] for dtb in d.getVar('KERNEL_DEVICETREE').split()])} tee.bin"
BOOTIMG_DIR = "${DEPLOY_DIR_IMAGE}"

# Let U-Boot provide a boot container (flash.bin) instead of imx-boot
UBOOT_PROVIDES_BOOT_CONTAINER = "1"

# In each NXP machine conf
MACHINEOVERRIDES =. "nxp:"

# "zImage" not supported on arm64 and ".gz" images not supported by bootloader yet
KERNEL_IMAGETYPE_DIRECT ?= "Image"
KERNEL_BOOTCMD ?= "booti"

ARMSTUB ?= "armstub8-gic.bin"

VIRTUAL-RUNTIME_obmc-gpio-monitor = "obmc-gpio-monitor"

PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native = "imx-led-manager-config-native"

# Select implementations for OpenBMC management virtuals
VIRTUAL-RUNTIME_obmc-system-mgmt  ?= "phosphor-state-manager"
VIRTUAL-RUNTIME_obmc-chassis-mgmt ?= "phosphor-state-manager"
VIRTUAL-RUNTIME_obmc-host-mgmt    ?= "phosphor-state-manager"

WKS_FILE_DEPENDS += "imx-boot"