BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*.bbappend \
			${LAYERDIR}/recipes-*/*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aminuvton"
BBFILE_PATTERN_meta-aminuvton := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aminuvton = "21"
LAYERSERIES_COMPAT_meta-aminuvton = "walnascar"
LAYERDEPENDS_meta-aminuvton = "meta-ami evb-npcm845"
