#!/bin/bash

NVMP=/tmp/.rwfs

do_sync() {
    # Ensure the file responsible for monotonicity between boots is
    # refreshed. Firmware updates are completed by assertion of the
    # BMC reset input. This prevents timesyncd from gracefully
    # updating this file.
    touch /var/lib/systemd/timesync/clock
    rsync -a --numeric-ids --inplace --partial --delete -x \
    --exclude='**/var/volatile/tmp/**' --exclude='**/etc/nv-sync-enable**' --exclude='**/etc/sync-enable**' \
    /run/initramfs/rw/ $NVMP/
    sync $NVMP/cow
}

findmtd() {
	m=$(grep -xl "$1" /sys/class/mtd/*/name)
	m=${m%/name}
	m=${m##*/}
	echo "$m"
}

blkid_fs_type() {
	# Emulate util-linux's `blkid -s TYPE -o value $1`
	# Example busybox blkid output:
	#    # blkid /dev/mtdblock5
	#    /dev/mtdblock5: TYPE="squashfs"
	# Process output to extract TYPE value "squashfs".
	blkid "$1" | sed -e 's/^.*TYPE="//' -e 's/".*$//'
}

probe_fs_type() {
	fst=$(blkid_fs_type "$1")
	echo "${fst:=jffs2}"
}

stop_nv() {
    history -a
    do_sync
    mount -o remount,ro $NVMP
    exit 0
}

# register cleanup function
trap stop_nv SIGINT
trap stop_nv SIGTERM
trap stop_nv EXIT

mkdir -p $NVMP

rwfs=$(findmtd rwfs)
rwdev=/dev/mtdblock${rwfs#mtd}
rwopts=rw

# Mount the rwfs JFFS2 partition RW at /tmp/.rwfs
# This gives nv-syncd a second view of the NV storage to sync into,
# keeping /run/initramfs/rw (the live overlay upper) as the source of truth.
mount "$rwdev" $NVMP -t "$(probe_fs_type "$rwdev")" -o "$rwopts"

# Run rsync periodically to sync the overlay to NV storage
while true; do
    do_sync
    sleep 10
done
