
#LF Features
IMAGE_FEATURES = " "
IMAGE_FEATURES:append = " ${EXTRA_IMAGE_FEATURES} "

# Below are the Extension Packages (EPs) which can be enabled by including them in IMAGE_FEATURES.
# Each EP corresponds to a specific feature set and includes the necessary package group.
FEATURE_PACKAGES_onetree-brcmraid ?= "packagegroup-onetree-apps-brcmraid" 
FEATURE_PACKAGES_onetree-brcmraid8 ?= "packagegroup-onetree-apps-brcmraid8"
FEATURE_PACKAGES_onetree-nic ?= "packagegroup-onetree-apps-nic" 
FEATURE_PACKAGES_onetree-nvme ?= "packagegroup-onetree-apps-nvme" 
FEATURE_PACKAGES_onetree-nvmebasic ?= "packagegroup-onetree-apps-nvmebasic" 
FEATURE_PACKAGES_onetree-fwupdate ?= "packagegroup-onetree-apps-fwupdate" 
FEATURE_PACKAGES_onetree-brcmpciesw ?= "packagegroup-onetree-apps-brcmpciesw" 
FEATURE_PACKAGES_onetree-rtp ?= "packagegroup-onetree-apps-rtp" 
FEATURE_PACKAGES_onetree-msccraid ?= "packagegroup-onetree-apps-msccraid" 
FEATURE_PACKAGES_onetree-intel-pfr ?= "packagegroup-onetree-apps-intel-pfr" 
FEATURE_PACKAGES_onetree-gpgpu ?= "packagegroup-onetree-apps-gpgpu" 
FEATURE_PACKAGES_onetree-acd ?= "packagegroup-onetree-apps-acd" 
FEATURE_PACKAGES_onetree-asd ?= "packagegroup-onetree-apps-asd" 
FEATURE_PACKAGES_onetree-mrt ?= "packagegroup-onetree-apps-mrt" 
FEATURE_PACKAGES_onetree-amdremotedbg ?= "packagegroup-onetree-apps-amdremotedbg"
FEATURE_PACKAGES_onetree-intelsipack ?= "packagegroup-onetree-apps-intelsipack"
FEATURE_PACKAGES_onetree-kvm ?= "packagegroup-onetree-apps-kvm"
FEATURE_PACKAGES_onetree-media-redirect ?= "packagegroup-onetree-apps-media-redirect"
FEATURE_PACKAGES_onetree-jviewer ?= "packagegroup-onetree-apps-jviewer"
FEATURE_PACKAGES_onetree-webui ?= "packagegroup-onetree-apps-webui"
FEATURE_PACKAGES_onetree-amd-apml ?= "packagegroup-onetree-apps-amd-apml"
FEATURE_PACKAGES_onetree-amd-addc ?= "packagegroup-onetree-apps-amd-addc"
FEATURE_PACKAGES_onetree-amd-powercap ?= "packagegroup-onetree-apps-amd-powercap"
FEATURE_PACKAGES_onetree-amd-lcd ?= "packagegroup-onetree-apps-amd-lcd"
FEATURE_PACKAGES_onetree-sensors ?= "packagegroup-onetree-apps-sensors"
FEATURE_PACKAGES_onetree-power ?= "packagegroup-onetree-apps-power"
FEATURE_PACKAGES_onetree-phosphor-power ?= "packagegroup-onetree-apps-phosphor-power"
FEATURE_PACKAGES_onetree-gpio-presence ?= "packagegroup-onetree-apps-gpio-presence"
FEATURE_PACKAGES_onetree-fru ?= "packagegroup-onetree-apps-fru"
FEATURE_PACKAGES_onetree-sel ?= "packagegroup-onetree-apps-sel"
FEATURE_PACKAGES_onetree-postcode ?= "packagegroup-onetree-apps-postcode"
FEATURE_PACKAGES_onetree-pef-alert ?= "packagegroup-onetree-apps-pef-alert"
FEATURE_PACKAGES_onetree-snmp ?= "packagegroup-onetree-apps-snmp"
FEATURE_PACKAGES_onetree-smtp ?= "packagegroup-onetree-apps-smtp"
FEATURE_PACKAGES_onetree-sol ?= "packagegroup-onetree-apps-sol"
FEATURE_PACKAGES_onetree-session ?= "packagegroup-onetree-apps-session"
FEATURE_PACKAGES_onetree-radius-client ?= "packagegroup-onetree-apps-radius-client"
FEATURE_PACKAGES_onetree-license ?= "packagegroup-onetree-apps-license"
FEATURE_PACKAGES_onetree-backup-restore ?= "packagegroup-onetree-apps-backup-restore"
FEATURE_PACKAGES_onetree-host-error ?= "packagegroup-onetree-apps-host-error"
FEATURE_PACKAGES_onetree-thermal-mgnt ?= "packagegroup-onetree-apps-thermal-mgnt"
FEATURE_PACKAGES_onetree-ntp ?= "packagegroup-onetree-apps-ntp"
FEATURE_PACKAGES_onetree-slpd ?= "packagegroup-onetree-apps-slpd"
FEATURE_PACKAGES_onetree-lldpd ?= "packagegroup-onetree-apps-lldpd"
FEATURE_PACKAGES_onetree-bootlogo ?= "packagegroup-onetree-apps-bootlogo"
FEATURE_PACKAGES_onetree-2fa ?= "packagegroup-onetree-apps-2fa"
FEATURE_PACKAGES_onetree-prov-mode-mgr ?= "packagegroup-onetree-apps-prov-mode-mgr"
FEATURE_PACKAGES_onetree-rbc-mgr ?= "packagegroup-onetree-apps-rbc-mgr"
FEATURE_PACKAGES_onetree-spdm ?= "packagegroup-onetree-apps-spdm" 
FEATURE_PACKAGES_onetree-intel-mctp ?= "packagegroup-onetree-apps-intel-mctp" 
FEATURE_PACKAGES_onetree-intel-pldm ?= "packagegroup-onetree-apps-intel-pldm" 
FEATURE_PACKAGES_onetree-host-interface ?= "packagegroup-onetree-apps-host-interface" 
FEATURE_PACKAGES_onetree-extlog ?= "packagegroup-onetree-apps-extlog"
FEATURE_PACKAGES_onetree-mctp-i3c-sock ?= "packagegroup-onetree-apps-mctp-i3c-sock"
FEATURE_PACKAGES_onetree-bmc-services-ready ?= "packagegroup-onetree-apps-bmc-services-ready"
FEATURE_PACKAGES_onetree-pdk ?= "packagegroup-onetree-apps-pdk"
FEATURE_PACKAGES_onetree-telemetry ?= "packagegroup-onetree-apps-telemetry"
FEATURE_PACKAGES_onetree-ipmb ?= "packagegroup-onetree-apps-ipmb"

# NVIDIA Features
FEATURE_PACKAGES_onetree-nvidiasipack ?= "packagegroup-onetree-apps-nvidiasipack"

# ARM Common Features
FEATURE_PACKAGES_onetree-ipmi-ssif ?= "packagegroup-onetree-apps-ipmi-ssif"

# Network Features
FEATURE_PACKAGES_onetree-network ?= "packagegroup-onetree-apps-network"
FEATURE_PACKAGES_onetree-network-system-firewall-support ?= "packagegroup-onetree-apps-network-system-firewall-support"
FEATURE_PACKAGES_onetree-network-advanced-route-support ?= "packagegroup-onetree-apps-network-advanced-route-support"
FEATURE_PACKAGES_onetree-network-bonding-support ?= "packagegroup-onetree-apps-network-bonding-support"
FEATURE_PACKAGES_onetree-network-openssl-support ?= "packagegroup-onetree-apps-network-openssl-support"
FEATURE_PACKAGES_onetree-network-disable-ping-support ?= "packagegroup-onetree-apps-network-disable-ping-support"
FEATURE_PACKAGES_onetree-network-iperf3-support ?= "packagegroup-onetree-apps-network-iperf3-support"
FEATURE_PACKAGES_onetree-network-ncsi-support ?= "packagegroup-onetree-apps-network-ncsi-support"
FEATURE_PACKAGES_onetree-network-phy-configuration-support ?= "packagegroup-onetree-apps-network-phy-configuration-support"
FEATURE_PACKAGES_onetree-network-nsupdate-support ?= "packagegroup-onetree-apps-network-nsupdate-support"
FEATURE_PACKAGES_onetree-network-tsig-support ?= "packagegroup-onetree-apps-network-tsig-support"
FEATURE_PACKAGES_onetree-network-persist-mac-support ?= "packagegroup-onetree-apps-network-persist-mac-support"
FEATURE_PACKAGES_onetree-network-avahi-support ?= "packagegroup-onetree-apps-network-avahi-support"
FEATURE_PACKAGES_onetree-network-ncsi-non-aen-support ?= "packagegroup-onetree-apps-network-ncsi-non-aen-support"
FEATURE_PACKAGES_onetree-network-ncsi-channel-timer ?= "packagegroup-onetree-apps-network-ncsi-channel-timer"
FEATURE_PACKAGES_onetree-network-ncsi-asycn-reset-support ?= "packagegroup-onetree-apps-network-ncsi-async-reset-support"

# Firmware update core features
FEATURE_PACKAGES_onetree-fwupdate-cpld-update ?= "packagegroup-onetree-apps-fwupdate-cpld-update "
FEATURE_PACKAGES_onetree-image-sign ?= "packagegroup-onetree-apps-image-sign"
FEATURE_PACKAGES_onetree-dual-image ?= "packagegroup-onetree-apps-dual-image"
FEATURE_PACKAGES_onetree-hw-failsafe-boot ?= "packagegroup-onetree-apps-hw-failsafe-boot"
FEATURE_PACKAGES_onetree-single-spi-abr ?= "packagegroup-onetree-apps-single-spi-abr"
FEATURE_PACKAGES_onetree-sync-conf ?= "packagegroup-onetree-apps-sync-conf"
FEATURE_PACKAGES_onetree-phosphor-ipmi-flash ?= "packagegroup-onetree-apps-phosphor-ipmi-flash"

#Tools
FEATURE_PACKAGES_onetree-tools ?= "packagegroup-onetree-apps-tools"

# PLDM core feature
FEATURE_PACKAGES_onetree-pldm ?= "packagegroup-onetree-apps-pldm"

FEATURE_PACKAGES_onetree-multi-host-support ?= "packagegroup-onetree-apps-multi-host-support"

# Rack Manager and Power Shelf features
FEATURE_PACKAGES_onetree-rm ?= "packagegroup-onetree-apps-rm"
FEATURE_PACKAGES_onetree-psm ?= "packagegroup-onetree-apps-psm"
