# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nuvoton"
BBFILE_PATTERN_nuvoton := "^${LAYERDIR}/"
LAYERVERSION_nuvoton = "1"
LAYERSERIES_COMPAT_nuvoton = "walnascar"
LAYERDEPENDS_nuvoton:append:npcm8xx = " meta-arm"
EXTRA_IMAGE_FEATURES:append = " onetree-media-redirect"
BBFILE_PRIORITY_nuvoton = "11"

ENABLE_BONDING = "network-bond"
