BBPATH .= ":${LAYERDIR}"

BBFILES += "\
${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "evb-fvp-base"
BBFILE_PATTERN_evb-fvp-base = "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-fvp-base = "15"
LAYERSERIES_COMPAT_evb-fvp-base = "walnascar"

#Disable Multi-SOL
MULTI_SOL_ENABLED = "0"

EXTRA_IMAGE_FEATURES:remove = "\
    onetree-kvm \
    onetree-media-redirect \
    onetree-jviewer \
    onetree-2fa \
    onetree-fru \
    onetree-host-interface \
"

LF_CORE_FEATURES:append ?= " obmc-dmtf-pmci obmc-telemetry"
IMAGE_INSTALL:remove = " hw-watchdog "
