# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-nuvoton-npcm845"
BBFILE_PATTERN_evb-nuvoton-npcm845 = "^${LAYERDIR}/"
LAYERSERIES_COMPAT_evb-nuvoton-npcm845 = "walnascar"
IMAGE_INSTALL:append = "${@bb.utils.contains('IMAGE_FEATURES', 'onetree-fwupdate', ' nv-sync ','', d)}"
BBFILE_PRIORITY_evb-nuvoton-npcm845 = "11"
