#!/bin/sh

retry=0
while [ $retry -lt 10 ]; do
    hostconf_result=$(busctl get-property xyz.openbmc_project.Network /xyz/openbmc_project/network/dns xyz.openbmc_project.Network.DDNS HostConf 2>/dev/null)
    [ $? -eq 0 ] && break
    sleep 1
    retry=$((retry + 1))
done

if [ $? -eq 0 ]; then
    auto_mode=$(echo "$hostconf_result" | awk '{print $2}')
    if [ "$auto_mode" != "true" ] && [ -f /etc/hostname ]; then
        manual_hostname=$(cat /etc/hostname)
        [ "$(hostname)" != "$manual_hostname" ] && hostnamectl set-hostname "$manual_hostname"
        exit 0
    fi
elif [ -f /etc/hostname ]; then
    file_hostname=$(cat /etc/hostname)
    if [ "$file_hostname" != "intel-obmc" ] && [ "$(hostname)" != "$file_hostname" ]; then
        hostnamectl set-hostname "$file_hostname"
        exit 0
    fi
fi

hostname=$(hostname)
hw_mac=$(cat /sys/class/net/eth0/address | tr -d ":")
bmc_mac_format="^AMIOT-[a-f0-9]{12}$"
mac_default="AMIOT-$hw_mac"
if [ "$hostname" = "intel-obmc" ] || [ "$hostname" = "ast2700-default" ] || [ "$hostname" = "AMIOT" ]; then
	hostnamectl set-hostname "$mac_default"	
fi
