# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb"
BBFILE_PATTERN_evb = ""
LAYERSERIES_COMPAT_evb = "walnascar"
MULTI_SOL_ENABLED = "1"
ENABLE_BONDING = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'onetree-network-bonding-support', 'network-bond', '', d)}"
