# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
			${LAYERDIR}/recipes-*/*/*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-imx95"
BBFILE_PATTERN_evb-imx95 = "^${LAYERDIR}/"

LAYERSERIES_COMPAT_evb-imx95 = "walnascar scarthgap"
BBFILE_PATTERN_IGNORE_EMPTY_evb-imx95 = "1"

AMI_CORE_FEATURES:remove = "onetree-kvm"

IMAGE_INSTALL:append = " libmodbus curl usbutils"

