# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb-aspeed"
BBFILE_PATTERN_evb-aspeed = ""

LAYERSERIES_COMPAT_evb-aspeed = "walnascar"
IMAGE_INSTALL:append = "${@bb.utils.contains('IMAGE_FEATURES', 'onetree-fwupdate', ' nv-sync ','', d)}"
IMAGE_INSTALL:remove = "${@bb.utils.contains('IMAGE_FEATURES', 'onetree-dual-image-common-conf', ' nv-sync ','', d)}"

BBMASK += '${@bb.utils.contains("BBFILE_COLLECTIONS", "restricted", "/meta-core/meta-restricted/recipes-intel/images/intel-platforms.bbappend", "",d)}'
EXTRA_IMAGE_FEATURES:remove = '${@bb.utils.contains("BBFILE_COLLECTIONS", "restricted", "    onetree-acd \
    onetree-mrt \
    onetree-intelsipack ", "",d)}'

EXTRA_IMAGE_FEATURES:remove = '${@bb.utils.contains("BBFILE_COLLECTIONS", "restricted", "  \
	oob-config-features \
	seamless-featurs \
	testability-features ", "",d)}'

