# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb-aspeed"
BBFILE_PATTERN_evb-aspeed = ""

LAYERSERIES_COMPAT_evb-aspeed = "nanbield scarthgap"

BBMASK += '${@bb.utils.contains("BBFILE_COLLECTIONS", "restricted", "/openbmc-meta-intel/meta-restricted/recipes-intel/images/intel-platforms.bbappend", "",d)}'
EXTRA_IMAGE_FEATURES:remove = '${@bb.utils.contains("BBFILE_COLLECTIONS", "restricted", "    acd-features \
    mrt-features \
    nm-features \
    oob-config-features \
    ras-offload-features \
    seamless-features \
    telemetry-features \
    testability-features ", "",d)}'

IMAGE_INSTALL:append = " intel-ipmi-oem webui-vue virtual-media phosphor-gpio-monitor "
IMAGE_INSTALL:append = '${@bb.utils.contains("EXTRA_IMAGE_FEATURES", "use-lfmctp", "", " pmci-launcher nvmemi-daemon pldmd mctpd ",d)}'

