[libdefaults]
	default_realm = CORE.SERVER.COM
	admin_server = CORE.SERVER.COM
	kdc = CORE.SERVER.COM
        default_keytab_name = /etc/krb5.keytab
# The following krb5.conf variables are only for MIT Kerberos.
	kdc_timesync = 1
	ccache_type = 4
	forwardable = true
	proxiable = true
	default_ccache_name = FILE:/tmp/krb5cc_%{uid}
	rdns = false
	dns_lookup_realm = true
	dns_lookup_kdc = true
	default_tkt_enctypes = aes256-cts aes128-cts rc4-hmac
	default_tgs_enctypes = aes256-cts aes128-cts rc4-hmac
	permitted_enctypes = aes256-cts aes128-cts rc4-hmac
# The following encryption type specification will be used by MIT Kerberos
# if uncommented.  In general, the defaults in the MIT Kerberos code are
# correct and overriding these specifications only serves to disable new
# encryption types as they are added, creating interoperability problems.
#
# The only time when you might need to uncomment these lines and change
# the enctypes is if you have local software that will break on ticket
# caches containing ticket encryption types it doesn't know about (such as
# old versions of Sun Java).

#	default_tgs_enctypes = des3-hmac-sha1
#	default_tkt_enctypes = des3-hmac-sha1
#	permitted_enctypes = des3-hmac-sha1

# The following libdefaults parameters are only for Heimdal Kerberos.
	fcc-mit-ticketflags = true

[realms]
	CORE.SERVER.COM = {
		kdc = win-o0lbjaidqgs.core.server.com
		admin_server = win-o0lbjaidqgs.core.server.com
		default_domain = win-o0lbjaidqgs.core.server.com
	}

[domain_realm]
	 core.server.com = CORE.SERVER.COM
	.core.server.com = CORE.SERVER.COM

[appdefaults]
        pam = {
        ticket_lifetime         = 1d
        renew_lifetime          = 1d
        forwardable             = true
        proxiable               = false
        retain_after_close      = false
        minimum_uid             = 0
        debug                   = false
        }
